@@include('jquery.min.js');
@@include('menu.js');
@@include('map.js');
@@include('lang.js');
@@include('tabs.js');
@@include('slick.min.js');
@@include('slider.js');
@@include('accordion.js');
@@include('up.js');